### ISSUE TITLE
problems with saving plot 

### ISSUE THREAD

**Issue by gabriellayi** [bernatgel/karyoploteR#100]
Hi,

I have a question about saving density plots into PDF or svs format for publications. I tried the basic saving code which didn't work. I'm wondering how you saved the plots for publication. 

Thanks!!

Yi

**Comment by bernatgel** [comment]
Hi Yi, 

I' don't know what you mean by "basic saving code and how it didn't work (did produce any error message? or just did nothing?)

I don't know if this is your case, but some users have been trying to save the plot using ggsave or similar functions. These won't work because karyoploteR  is not a ggplot2 object, but a base graphic.

To save a karyoploteR plot you new to open a graphical device (`svg`, `png`, `pdf`...) then plot as usual `kp <- plotKaryotype(...)` and then close the graphical device. You can see an example saving to png's at https://github.com/bernatgel/karyoploteR_questions/blob/master/biostars_488503/biostars_488503.R

IMPORTANT: both svg and pdf specify the size of the plot in inches instead of pixels, so for those types, 7 is a much more sensible number than 1000!!!

**Comment by gabriellayi** [comment]
Hi Bernatgel,
When I used the code that you used in your example, nothing happened. 
I think because I merged two gene sets in one density plot, please see the code below:

pdf("density.pdf")
  kp <- plotKaryotype(genome="mm10",plot.type=1,ideogram.plotter = NULL)
  color1 <- transparent("blue", amount= 0.6)
  color2 <- transparent("red", amount= 0.8)
  kpAddCytobandsAsLine(kp)
  kpAddChromosomeNames(kp)
  kpPlotDensity(kp, data = genes, r0=0, r1=2, col=color1,border="blue",     data.panel=2)
  kpPlotDensity(kp, data = genes2,r0=0, r1=2, col=color2,border="red",data.panel=2)
dev.off()
The error is: null device 1

The only operation I can do is right-click the image and save it as svs or tif files. 

Thanks!
Yi

**Comment by bernatgel** [comment]
Hi Yi,

I'm sure the problem has nothing to do with plotting the two sets of genes,
and probably not much to do with karyoploteR.

I'd suggest performing a series of tests to identify the problem:

    1  - run `getwd()` to be sure that you don't see density.pdf in that
directory.

    2 - run

          pdf("test.pdf")
          plot(0,0)
          dev.off()

          and see if the file exists. If it does not, try running
"dev.off()" a few times to be sure there are no open graphical devices.and
try running it again.

    3 - If the code above worked, try the same but with plotKaryotype
instead of plot.

    4  - If 3 worked, then try again adding the rest of your code and see
what happens

Bernat
