### ISSUE TITLE
Error in loading custom genome

### ISSUE THREAD

**Issue by jeff-godwin** [bernatgel/karyoploteR#101]
Hello Bernat. 
I'm facing an issue while loading the Bos taurus genome.

My run is-

> kp <- plotKaryotype(genome="bosTau9")
The masked version of 'bosTau9' is not installed. Using the unmasked version. This means that no automatic masking will be available.
[1] "bosTau9"
Loading ideogram...
Error in normArgTrack(track, trackids) : Unknown track: cytoBand
cytoBand informatin is not available, only get ranges.
Loading ranges...
Done
Error in `[[<-`(`*tmp*`, name, value = character(0)) : 
  0 elements in value to replace 2211 elements

Previous versions of the genome give the same error message. 
Any ideas why? Thanks

**Comment by kmaniates** [comment]
I'm having the same error for the C. elegans genome: 

 kp <- plotKaryotype(genome = "ce11")
[1] "ce11"
Loading ideogram...
Error in normArgTrack(track, trackids) : Unknown track: cytoBand
cytoBand informatin is not available, only get ranges.
Loading ranges...
Done
Error in `[[<-`(`*tmp*`, name, value = character(0)) : 
  0 elements in value to replace 7 elements

Were you ever able to solve this error message?

**Comment by jeff-godwin** [comment]
No, I couldn't solve it. I generated an image by creating a custom genome. 
You can find the steps at - https://bernatgel.github.io/karyoploter_tutorial//Tutorial/CustomGenomes/CustomGenomes.html

**Comment by bernatgel** [comment]
Hi all,

The problem is that it is not getting the cytobands from UCSC and it's choking with it. This is a bug I'll have to hunt down. 

However you can use an "automatic" custom genome with something like this.

bos.genome <- getGenome("bosTau9")
#Filter out the non-canonical chromosomes. Since these assemblies have hundreds of them.
bos.genome <- filterChromosomes(bos.genome, organism = "bosTau", chr.type = "canonical")
kp <- plotKaryotype(genome=bos.genome)

This will create a valid and working karyoplot, but without cytobands (all chromosomes will be plain gray). If you have the coordinates for the cytobands yourself you can pass the to plotKaryotype and it will use them. 

This temporary workaround should work with c. elegans too. 

Hope this helps.

**Comment by jeff-godwin** [comment]
Cheers Bernat. I did the same and my plot came out quite well. Great package.

**Comment by bernatgel** [comment]
Great, happy it helped :)
