### ISSUE TITLE
kpArea is in documentaiton but not package

### ISSUE THREAD

**Issue by map2085** [bernatgel/karyoploteR#12]
> > library(karyoploteR)
> > kpArea()
> Error in kpArea() : could not find function "kpArea"
> > ?kpArea
> No documentation for 'kpArea' in specified packages and libraries:

However, it is in the documentation at Bioconductor

**Comment by bernatgel** [comment]
Hi @map2085 
What version are you using? kpArea was added in the latest release version (1.6.0). This is the version you will get from biocLite with the latest Bioconductor (3.7) released a few weeks ago. I think you might be using an old version of karyoploteR.

**Comment by map2085** [comment]
```
> source("https://bioconductor.org/biocLite.R")
Bioconductor version 3.5 (BiocInstaller 1.26.1), ?biocLite for help
A newer version of Bioconductor is available for this version of R, ?BiocUpgrade for help

> biocLite("karyoploteR")
> library(karyoploteR)

> sessionInfo()
R version 3.4.0 (2017-04-21)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.9 (Final)

karyoploteR_1.2.2 
```

**Comment by bernatgel** [comment]
yes, the problem is that youare using an old version of Bioconductor and thus an old version of karyoploteR.

As you can see at: 

"Bioconductor version 3.5 (BiocInstaller 1.26.1), ?biocLite for help
A newer version of Bioconductor is available for this version of R, ?BiocUpgrade for help"

If you want to use kpArea you'll have to upgrade your setup.
