### ISSUE TITLE
How to get plot name?

### ISSUE THREAD

**Issue by DC-Jade** [bernatgel/karyoploteR#130]
Hello, a very nice tool!

I want to arrange plot in karyoplotR with other plots in ggplot2 into the same graph.
so I **need the plot name, but I don't how to get it**,
would you like to help me deal with this issue
Thank u!

**Comment by twillis209** [comment]
Hi Jade

Have a look at this issue: https://github.com/bernatgel/karyoploteR/issues/51

Might be easiest to encapsulate the `karyoploteR` plot in a grob and combine it with your others.

**Comment by bernatgel** [comment]
Hi @DC-Jade 

@twillis209 is right, following the example in that issue is the way to go. karyoploteR is not based on ggplot but on base R graphics, so to combine it with it with ggplot2 graphics you'll need to encapsulate first. Using the first approach proposed in issue 51 should work for you, but if you have any problem with that, just ask :)

Bernat
