### ISSUE TITLE
kpBars will not change colors!

### ISSUE THREAD

**Issue by shalvichirmade** [bernatgel/karyoploteR#131]
Hello!

I was wondering if you could either point out my mistake or let me know why the colors of kpBars will not change when specified.

I have attached a picture to show that it defaults to black even when col = "lightsteelblue3" is mentioned (this is a color in baseR). As we can also see, the baseR col function has been working when using the kpPlotLoess to create the red line.

Here is a snippet of the code used to create the kpBars section:

plot.params <- getDefaultPlotParams(plot.type = 1)
plot.params$ideogramheight <- 5

kp2 <- plotKaryotype(chromosomes = "chr5",
                      zoom = "chr5:450000-500000",
                      plot.type = 1,
                      plot.params = plot.params)  
kpBars(kp2, chr = "chr5",
         r0 = 0.3, 
         r1 = 0.7,
         x0 = start(gr2),
         x1 = end(gr2),
         y1 = gr2$Discretized_Modification_Probability_100,
         col = "lightsteelblue3",
         clipping = T)

gr2 is a GRanges object.

Thank you!

![kpBars](https://user-images.githubusercontent.com/92757717/205344784-46da07f4-2f25-4f17-bf2e-c96aa2dff025.png)

**Comment by bernatgel** [comment]
Hi @shalvichirmade 

I think the problem here is one I've encountered quite a few times myself. Basically the bars are so thin that only the border is visible and it completely covers the actual blue bar. You could try assigning the same color to the border (`border= "lightsteelblue3"`) or removing the border (`border=NA`). Although with this second option coms bars could become invisible if small enough so I'd recommend the first one.

Hope this helps!

Bernat

**Comment by shalvichirmade** [comment]
Hi Bernat,

Thank you so much for the solution! It worked perfectly.

Shalvi
