### ISSUE TITLE
plots bams that have no "chr"

### ISSUE THREAD

**Issue by anuravi1234** [bernatgel/karyoploteR#133]
hello

I have a bam file for hg19 but the bam file do not have a "chr" for the chromosome. 

kp <- plotKaryotype(genome="hg19", chromosomes=c("chr20"),plot.type = 2)

kp <- kpPlotBAMDensity(kp,
                       "WGStest_100022508634_dedup-sorted-tag_bqsr.bam",
                       normalise=TRUE)

I get an error "Error in .io_bam(.count_bamfile, file, param = param) : 
  seqlevels(param) not in BAM header:
    seqlevels: 'chr20'"

Is there a way to plot to hg19 without the "chr" or should I provide a custom chr?

**Comment by bernatgel** [comment]
Hi @anuravi1234 

The problem you are seeing is indeed derived from different chromosome names. 

The easiest solution to this would be to get a custom genome from the hg19 genome and then use that one to create your plot. However, if you do this you will get an unexpected result, since it will plot ALL chromosomes in the assembly including all ALT chromosomes. The default options in `plotKaryotype` usually take care of this, but they do not apply for custom genomes.

```
my.hg19 <- getGenome("hg19")
kp <- plotKaryotype(genome=my.hg19)
```
![custom_hg19_no_filtering_no_cytobands](https://raw.githubusercontent.com/bernatgel/karyoploteR_questions/master/github_133/custom_hg19_no_filtering_no_cytobands.png)

Adding a simple filtering step will remove those. You can use the `filterChromosomes` from the [regioneR]() package (already available if you are using karyoploteR) and tell it its from a human (`organism="hg19"`) and you only want the canonical chromosomes (`chr.type="canonical"`) and you'll get closer to what you want

 ```
my.hg19 <- getGenome("hg19")
my.hg19 <- filterChromosomes(my.hg19, organism = "hg", chr.type = "canonical")
kp <- plotKaryotype(genome=my.hg19)
```

![custom_hg19_filtering_no_cytobands](https://raw.githubusercontent.com/bernatgel/karyoploteR_questions/master/github_133/custom_hg19_filtering_no_cytobands.png)

Then, we have to get the cytobands with `getCytobands` (again, this is automatically done when using a non-custom genome) and add them to the plot. With that, we are where we started but using a custom genome.

```
my.hg19 <- getGenome("hg19")
my.hg19 <- filterChromosomes(my.hg19, organism = "hg", chr.type = "canonical")
my.cytobands <- getCytobands("hg19")
kp <- plotKaryotype(genome=my.hg19, cytobands = my.cytobands)
```
![custom_hg19_filtering_cytobands](https://raw.githubusercontent.com/bernatgel/karyoploteR_questions/master/github_133/custom_hg19_filtering_cytobands.png)


And now, we can use the `seqlevelsStyle` function to set the style of the chromosome names to "Ensembl", that is, without the "chr".

```
my.hg19 <- getGenome("hg19")
my.hg19 <- filterChromosomes(my.hg19, organism = "hg", chr.type = "canonical")
seqlevelsStyle(my.hg19) <- "Ensembl"
my.cytobands <- getCytobands("hg19")
seqlevelsStyle(my.cytobands) <- "Ensembl"
kp <- plotKaryotype(genome=my.hg19, cytobands = my.cytobands)
```

![custom_hg19_filtering_cytobands_no_chr](https://raw.githubusercontent.com/bernatgel/karyoploteR_questions/master/github_133/custom_hg19_filtering_cytobands_no_chr.png)

And now `kpPlotBAMDensity` should work without any problem.

Seeing that this is a recurrent difficulty that many users face, I think it would be a good idea to add an option to `plotKaryotype` to perform this change internally, but so far the option is not available.

Hope this helps!

**Comment by anuravi1234** [comment]
Thanks!! this worked perfectly!..
