### ISSUE TITLE
lower R  version

### ISSUE THREAD

**Issue by Sisov** [bernatgel/karyoploteR#2]
I want to install the R package KaryoploteR while the R version is too lower ,Did there any method can solve it ,since there is so many R package in my R  that I don't want to update my R version. Thanks 

Alex

**Comment by bernatgel** [comment]
I'm sorry but it's not possible. As most Bioconductor packages, karyoploteR uses functionality from many other Bioconductor packages. These packages change and evolve and so they are only guaranteed to work with the correct Bioconductor (and therefore, R) version. 
It's in general a good advice to update your R and Bioconductor versions, since you will be able to take advantage of the latest bug fixes and new features, but it's obviously up to you!

**Comment by Sisov** [comment]
Thanks ,I have update my R version to 3.4.1. well the software is so good to plot the pictures but I haven't see any legend to the pictures .so How to add the legend to the pictures.

**Comment by bernatgel** [comment]
Glad it worked for you.

Right now there is no specific function to plot a legend in karyoploteR. However, since a karyoplot is a standrad R plot you can just use the standard "legend" function to add a legend to a plot. You'll have to take care of the positioning, etc,, by yourself, but it should work.

Running something like

legend(x = "bottomright", legend=c("Group 1", "Group 2"))

after you have created your plot should do the trick.

Remember that you can always use "kpAddLabels" to add a text identifying different parts of the plot (this function is not yet in the tutorial).

**Comment by Sisov** [comment]
Thanks much .but I'm so sorry to bother you again ,since I want to use my customer genome to plot the SNP density ,while plot the cytobands there is no color for the different types of SNP  and appear a white box

**Comment by bernatgel** [comment]
Hi Sisov. I do not understand exactly what you would like to do and whats exactly is your problem. 
I would suggest that you create a new question in [biostars](https://www.biostars.org/) with some of the code you are using and maybe an image of what you are getting so I can try to help you.

**Comment by Sisov** [comment]
I have now solved it.Thanks ,bernatgel,the package is so good ,thanks for your reply
Alex

**Comment by bernatgel** [comment]
Great :)

Glad you find it useful
