### ISSUE TITLE
plot.new has not been called yet

### ISSUE THREAD

**Issue by andyjslee** [bernatgel/karyoploteR#25]
When I run the following:
My code:
```{r}
pp <- getDefaultPlotParams(plot.type = 4)
pp$data1max <- 1
kp <- plotKaryotype(zoom = toGRanges(data.frame("chr1", 1, 1e6)),
                    main = "",
                    plot.params = pp,
                    cytobands = NULL)
kpDataBackground(kp, data.panel = 1, col = "#FFFFFF")
```
I get the following error
```
Error in (function (x0, y0, x1 = x0, y1 = y0, col = par("fg"), lty = par("lty"),  : 
  plot.new has not been called yet
```
Fyi, I get the same error if I call ```kpBars``` or ```kpAxis```

sessionInfo()
```
R version 3.4.4 (2018-03-15)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 16.04.5 LTS

Matrix products: default
BLAS: /usr/lib/libblas/libblas.so.3.6.0
LAPACK: /usr/lib/lapack/liblapack.so.3.6.0

locale:
 [1] LC_CTYPE=en_US.UTF-8      
 [2] LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                 
 [9] LC_ADDRESS=C              
[10] LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8
[12] LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats    
[4] graphics  grDevices utils    
[7] datasets  methods   base     

other attached packages:
 [1] ballgown_2.10.0                        
 [2] TxDb.Hsapiens.UCSC.hg19.knownGene_3.2.2
 [3] GenomicFeatures_1.30.3                 
 [4] AnnotationDbi_1.40.0                   
 [5] Biobase_2.38.0                         
 [6] karyoploteR_1.9.1                      
 [7] regioneR_1.10.0                        
 [8] BSgenome_1.46.0                        
 [9] Biostrings_2.46.0                      
[10] XVector_0.18.0                         
[11] memoise_1.1.0                          
[12] rtracklayer_1.38.3                     
[13] GenomicRanges_1.30.3                   
[14] GenomeInfoDb_1.14.0                    
[15] IRanges_2.12.0                         
[16] S4Vectors_0.16.0                       
[17] BiocGenerics_0.24.0                      
```

**Comment by bernatgel** [comment]
Running your code works perfectly fine for me...

Err... are you running them in an Rmarkdown document? If so, instead of selecting and running each line individually, select the whole chunk (or at least from `plotKaryotype` until the the last plotting function) and run them at once. 

If you are using a standard R script, did you close the plot after running plotKaryotype and before running kpDataBackground?

**Comment by andyjslee** [comment]
Thank you for your response. I was able to run it successfully based on your response. Now I am having another issue where I want to plot the kpPlotGenes below the graph. I am using plot.type = 2 and am getting the following error:
```
Error in ccf(chr = c(chr, chr), x = 0, y = c(0, t.mark.height)) : 
  If x is not NULL, it have to have the same length as chr
```

Here is my code for your reference:

```
par(mar=c(1,1,1,1))
plot.new()
pp <- getDefaultPlotParams(plot.type = 3)
pp$data1max <- 10
pp$data2max <- 10
kp <- plotKaryotype(zoom = toGRanges(data.frame("chr1", 1, 1e6)),
                    plot.type = 3,
                    main = "",
                    plot.params = pp,
                    ideogram.plotter = NULL)
kpDataBackground(kp, data.panel = 1, col = "#FFFFFF")
kpAxis(kp, r1 = 10, ymin = 0, ymax = 10, numticks = 5, cex = 1, data.panel = 1, side = 1)
kpPlotGenes(kp, data = TxDb.Hsapiens.UCSC.hg19.knownGene, plot.transcripts = T, data.panel = 2, r0 = 1, r1 = 3)

```

**Comment by bernatgel** [comment]
I can reproduce the problem. 
I'll have to take a deeper look at it to see what's happening.

**Comment by andyjslee** [comment]
Thank you so much for looking into this. I really appreciate all your help and your awesome package!

**Comment by andyjslee** [comment]
Also, when I call kpPlotMarkers without calling kpPlotGenes, I get the following error:
```
Error in karyoplot$getDataPanelBoundingBox(data.panel) : 
  attempt to apply non-function
```
I ran a script that worked fine in karyoploteR version 1.4.2 (from Bioconductor), and am getting that error now.

**Comment by bernatgel** [comment]
Ok, there where a cuople of bugs due to recent changes for Bioconductor release! Thanks for reporting this.

The newest version in github (1.9.2) should work now. If you have any other problem, please open an issue here so we can take a look 

In any case, ploease bear in mind that using the github version (from branch "master"), you are using the devel version of the package and that things will regularly break. Release branches are also available in github (latest one is branch "RELEASE_3_8") so you can use this if you want a more stable (less cutting edge) version of the package (bug fixes have also been applied to that branch).
