### ISSUE TITLE
Error to call function createRandomRegions()

### ISSUE THREAD

**Issue by yifangt** [bernatgel/karyoploteR#33]
Hello, when I was trying the [tutorial,](https://bernatgel.github.io/karyoploter_tutorial//Tutorial/PlotCoverage/PlotCoverage.html) I always met an error with the function **createRandomRegions()**.
```
regions <- createRandomRegions(nregions=10000, length.mean = 1e6, mask=NA)
Error in private_randomizeRegions(A = pending, genome = genome, mask = mask,  : 
  It was not possible to create a valid random region set after 5 retries. This might be due to the regions in A covering most of the available genome. Allowing overlapping random regions could solve this problem.
In addition: Warning messages:
1: In private_randomizeRegions(A = pending, genome = genome, mask = mask,  :
  It was not possible to create the random region set because there was no space available. Retrying.
2: In private_randomizeRegions(A = pending, genome = genome, mask = mask,  :
  It was not possible to create the random region set because there was no space available. Retrying.
3: In private_randomizeRegions(A = pending, genome = genome, mask = mask,  :
  It was not possible to create the random region set because there was no space available. Retrying.
4: In private_randomizeRegions(A = pending, genome = genome, mask = mask,  :
  It was not possible to create the random region set because there was no space available. Retrying.
5: In private_randomizeRegions(A = pending, genome = genome, mask = mask,  :
  It was not possible to create the random region set because there was no space available. Retrying.

```
I have installed the masked human genome hg19 by:
` install("BSgenome.Hsapiens.UCSC.hg19")`
Did I miss anything?

**Comment by bernatgel** [comment]
Hi @yifangt 

Thanks for reporting this. There was a change in [regioneR's](http://bioconductor.org/packages/regioneR/) `createRandomRegions` that changed the default value of `non.overlapping` parameter to TRUE. This caused this tutorial (and others) to fail. The problem was that the function was not able to place ten thousand 1 megabase regions in the genome without overlaps (which makes sense, since they would not fit into the genome!).

I've updated all tutorials and examples to take into account that and they all should work now with karyoploteR 1.8.6 and later.

Please, report if you find any other problem!

**Comment by vappiah** [comment]
Hi @bernatgel 
I am following your tutorial [plotting densities](https://bernatgel.github.io/karyoploter_tutorial//Tutorial/PlotDensity/PlotDensity.html)
When I try to use _createRandomRegions(nregions=10000, length.mean = 1e6, mask=NA, non.overlapping = FALSE)_
Attempt is made to install BSgenome.Hsapiens.UCSC.hg19 . This in turn attemps to update some R packages (more that 50 of them). 
Please advice on what to do since updating those packages may lead to other packages to fail.

Thanks
