### ISSUE TITLE
Error in plotting coverage of a bam file

### ISSUE THREAD

**Issue by c11cc** [bernatgel/karyoploteR#43]
Dear Bernat,

I met this problem in dealing with one bam file.
>library(karyoploteR)
gme <- toGRanges("D:/work/experiment/transposon/lxq/script/function_combine/chr_info.txt")
pp <- getDefaultPlotParams(plot.type=2)
pp$leftmargin<-0.1
fig1<-plotKaryotype(gme,chromosome="CP017553.1",plot.type=2,plot.params=pp)
kpAddBaseNumbers(fig1, tick.dist = 100000,add.units=TRUE)
bam1<-("D:/bioinformatics/gbib/shared/sample/d1-1.sorted.bam")
fig1 <- kpPlotBAMCoverage(fig1, data=bam1, r0=0,r1=1.,max.valid.region.size=2e8)
>kpAxis(fig1, ymax=fig1$latest.plot$computed.values$max.coverage, r0=0, r1=1)
> fig1$latest.plot$computed.values$max.coverage
[1] 228

The max coverage is 228. However, the plot showed as this, no value seemed to be larger than 144. I don't know what goes wrong.
![image](https://user-images.githubusercontent.com/24308368/57205389-e9642780-6ff0-11e9-82c6-3a1a6aff434a.png)

Besides, I wanted to extract the coverage data, but it only had one value. So, what should I do to get the data? 
>kpAxis(fig1, ymax=fig1$latest.plot$computed.values$max.coverage, r0=0, r1=1)
> fig1$latest.plot$computed.values
$max.coverage
[1] 228

Thank you for your time.

**Comment by bernatgel** [comment]
Hi @c11cc 

kpPlotBAMCoverage does not return the actual coverage values since they can take quite big in memory.

You can get the coverage information using the same code `kpPlotBamCoverage` uses: 

    bam.cov <- bamsignals::bamCoverage(bam.file, fig1$plot.region, verbose=FALSE)[1]

It will return an array of integers, with one integer per base visible base in your plot. 

Before deciding if the max.coverage value you get is a bug, can you try this and get the maximum value of the array? 

Thanks

Bernat

**Comment by c11cc** [comment]
@bernatgel 

> bam.cov <- bamsignals::bamCoverage(bam1, fig1$plot.region, verbose=FALSE)[1]
> max(bam.cov)
[1] 228


It worked this time. 

![image](https://user-images.githubusercontent.com/24308368/57216629-f39f1980-7022-11e9-8bce-90c246c563b7.png)

Besides, I tried this by removing  the "[1]", 

> bam.cov <- bamsignals::bamCoverage(bam1, fig1$plot.region, verbose=FALSE)
> max(bam.cov)
Error in max(bam.cov) : invalid 'type' (S4) of argument
 
I am wondering what is the function of "[1]"?

Thanks

**Comment by bernatgel** [comment]
Great, glad it worked. I think the problem was a visualization one. You are showing a very large region for coverage and the peaks are thin. Some of them might be so thin that may not be visible. An option in a situation like this, just to make sure every peak is visible, you can set `border="black"` and `lwd=2` in the call to `kpPlotBAMCoverage`. `border` is NA by default, removing the border of the coverage peaks. Making it black and wide (lwd=2) will make the small peaks much more clear.

With respect to your question, bamsignals returns an object of a specific class that has one element (one array of integers) for every range you give it. We are giving it a single range, so we want the first element, hence the [1]

Hope this helps

Bernat


(it usually would be better served by kpPlotBAMDensity, but it really depends on you aims (and preferences!))

**Comment by c11cc** [comment]
@bernatgel 
Thanks a lot, it looks much better now(lwd was not set)!
![image](https://user-images.githubusercontent.com/24308368/57265098-7ae2a080-70a8-11e9-82f0-faede003f5b1.png)

Besides, I tried kpPlotBAMDensity. To be honest, I prefer the result of kpPlotBAMCoverage.

**Comment by bernatgel** [comment]
Perfect, glad it helped :)
