### ISSUE TITLE
Problems in plotting gc content in a custom genome

### ISSUE THREAD

**Issue by c11cc** [bernatgel/karyoploteR#44]
Dear Bernat,
I feel so sorry to bother you twice in the same day. Here's another problem I met. I want to plot the GC content of a custom genome and I calculated it myself. However, I met problems when I tried to plot it with karyoploteR.

> library(karyoploteR)
> gme <-toGRanges("D:/work/experiment/transposon/lxq/script/function_combine/chr_info.txt")
> pp <- getDefaultPlotParams(plot.type=2)
> pp$leftmargin<-0.1
> fig1<-plotKaryotype(gme,chromosome="CP017553.1",plot.type=2,plot.params=pp)
> gc<-read.table(file="D:/bioinformatics/script/GC_content/gc.txt",head=TRUE)
> head(gc)
         chr      region GC_content
1 CP017553.1     1-10000     0.4808
2 CP017553.1 10001-20000     0.5055
3 CP017553.1 20001-30000     0.4829
4 CP017553.1 30001-40000     0.4592
5 CP017553.1 40001-50000     0.5001
6 CP017553.1 50001-60000     0.4657
> kpLines(fig1, data=gc, y=gc$GC_content)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'seqnames' for signature '"data.frame"'

Then I tried,

> gc<-DataFrame(gc)
> head(gc)
DataFrame with 6 rows and 3 columns
         chr      region GC_content
    <factor>    <factor>  <numeric>
1 CP017553.1     1-10000     0.4808
2 CP017553.1 10001-20000     0.5055
3 CP017553.1 20001-30000     0.4829
4 CP017553.1 30001-40000     0.4592
5 CP017553.1 40001-50000     0.5001
6 CP017553.1 50001-60000     0.4657
> kpLines(fig1, data=gc, y=gc$GC_content)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function 'seqnames' for signature '"DataFrame"'

I have no idea of what to do now.

Any help is appreciated.
Thanks.

**Comment by bernatgel** [comment]
Hi  @c11cc 

the data parameter in `kpLines` expects a GRanges object and you are giving it a data.frame (and a DataFrame in your second attempt) that's why it's failing.

You can build the GRanges with `toGRanges` (from package regioneR) and that should do it. However, it expects either a data.frame with columns for chr, start and end or a region definition string such as "CP017553.1:1-10000" but not the hybrid you have.

You need to split the second column on "-" or paste the first and the second one and then use toGRanges
 
    gc.gr <- toGRanges(paste0(gc[,1], ":", gc[,2]))
    gc.gr$GC <- gc[,3]

And use gc.gr instead of gc in `kpLines`. Oh, and make sure `GC_content` is a numeric and not a factor (I'd add "stringsAsFactors=FALSE" to read.table)

Bernat
