### ISSUE TITLE
Adjust.label.position

### ISSUE THREAD

**Issue by ridwan-shaikh** [bernatgel/karyoploteR#52]
Hi Bernat,

I have an issue with the kpPlotMarkers function where by the marker labels with adjust label position set to true is pushing the markers towards the end of the chromosome, even though there is enough space in the window to allow for the markers to be offset and be displayed next to each other (example below - data.panel=1 : adjust.label.position = T, data.panel=2 : adjust.label.position = F). I have also adjusted the label distance to be 0.1e-10 and max.iter=1e6 to ensure there are enough attempts to prevent over plotting in a whole genome plot.

![image](https://user-images.githubusercontent.com/48447625/64346894-e2731300-cfea-11e9-94de-81268b17385b.png)

Is there something that I am doing wrong?

Example dataset for the markers:
GRanges object with 193 ranges and 0 metadata columns:
         seqnames              ranges strand
            <Rle>           <IRanges>  <Rle>
  PIK3CD     chr1     9743657-9787145      *
    MTOR     chr1   11167475-11259494      *
  ARID1A     chr1   27022856-27107221      *
   CSF3R     chr1   36927412-36957939      *
    MYCL     chr1   40357974-40374442      *

**Comment by bernatgel** [comment]
Hi @ridwan-shaikh 

By default `kpPlotMarkers` will not cross the chromosome boundaries and so it will produce plots like this. You can set that off with `ignore.chromosome.ends=TRUE` although it does not guarantee that there will be no overlap with labels from the next chromosome since label repositioning is computed iteratively for each chromosome. At some point, I plan to upgrade the repositioning code but so far this is the only available option.
