### ISSUE TITLE
Could not find function "addGeneNames" and "mergeTranscripts"

### ISSUE THREAD

**Issue by Diwadkar** [bernatgel/karyoploteR#70]
Hi,

I have been trying to reproduce the tutorial as provided here: https://bernatgel.github.io/karyoploter_tutorial/Examples/EncodeEpigenetics/EncodeEpigenetics.html

I installed the package successfully, however, I get a "could not find function" error for both **addGeneNames(gene.data)** and **mergeTranscripts(gene.data)**. Is there any dependency I am missing? I have **attached my sessionInfo()** output. 

**My code:**
library(karyoploteR)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)

TP53.region <- toGRanges("chr17:7,564,422-7,602,719")
kp <- plotKaryotype(zoom = TP53.region)

genes.data <- makeGenesDataFromTxDb(TxDb.Hsapiens.UCSC.hg19.knownGene, karyoplot=kp, plot.transcripts = TRUE, plot.transcripts.structure = TRUE)

genes.data <- addGeneNames(genes.data)
genes.data <- mergeTranscripts(genes.data)

**The errors:**
Error in addGeneNames(genes.data) : could not find function "addGeneNames"
Error in mergeTranscripts(genes.data) : could not find function "mergeTranscripts"

<img width="1255" alt="sessionInfo()" src="https://user-images.githubusercontent.com/17258564/75917720-6ede8100-5e28-11ea-88fc-ff480db9fa00.png">

Thanks,
Avantika

**Comment by bernatgel** [comment]
Hi @Diwadkar 

The problem is that you are using an old version of karyoploteR (about 1 year old) and these functions were added more recently. The best approach would be to install the latest R version and install the latest version of karyoploteR from Bioconductor there. If it's not possible to install a newer R version, you can try installing it from github (`BiocManager::install("bernatgel/karyoploteR")`) but it may not work, since each version is conly tested against the relevant R versions.

**Comment by Diwadkar** [comment]
Yes, I updated my R version and the re-installed packaged worked perfectly! Thank you for your help!
